
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-06T21:58:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a1a725465401bc7e75d7797baddd65452608b8cb",
 "version": "0.0.1+2.ga1a7254"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
